---
ulm_global_config:
  variables:
    ulm_global_card_tap_action: "toggle"
    ulm_global_card_hold_action: "none"
    ulm_global_card_double_tap_action: "more-info"
    ulm_global_icon_tap_action: "none"
    ulm_global_icon_hold_action: "none"
    ulm_global_icon_double_tap_action: "none"
    ulm_global_name_tap_action: "none"
    ulm_global_name_hold_action: "none"
    ulm_global_name_double_tap_action: "none"
