---
name: "Codespell"

on:
  pull_request:
    branches: ["main", "release"]

jobs:
  codespell:
    name: "Check for spelling errors"
    runs-on: "ubuntu-latest"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: "actions/checkout@v2"
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: .codespell
          config: .codespellrc
